cursodjangoapp/cursodjangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
]

cursodjangoapp/polls/urls.py
from django.urls import path, include
from . import views

app_name = "polls"
urlpatterns = [
    #ex: /polls/
    path("", views.index, name = "index"),
    #ex: /polls/5 
    path("<int:question_id>/detail", views.detail, name = "detail"),
    #ex: /polls/5/results
    path("<int:question_id>/results/", views.results, name = "results"),
    #ex: /polls/5/vote 
    path("<int:question_id>/vote/", views.vote, name = "vote")
]

cursodjangoapp/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model): 
    question_text = models.CharField(max_length = 240)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
    

class Choise(models.Model): 
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choise_text = models.CharField(max_length = 300)
    votes = models.IntegerField(default = 0)
    
    def __str__(self):
        return self.choise_text
    

cursodjangoapp/polls/views.py
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse

from .models import Question

def index(request):
    latest_question_list = Question.objects.all()
    return render(request, "polls/index.html", {
        "latest_question_list": latest_question_list
    })

def detail(request, question_id):
    question = get_list_or_404(Question, pk = question_id)
    return render(request, "polls/detail.html", {
        "question": question
    })

def results(request, question_id):
    return HttpResponse(f"Estas viendo los resultado de la pregunta número {question_id}")

def vote(request, question_id):
    return HttpResponse(f"Estas votando a la pregunta número {question_id}")

cursodjangoapp/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message  %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}
    {% for choise in question.choise_set.all %}
        <input
            type="radio"
            name="choise"
            id="choise {{ forloop.counter }}"
            value="{{choise.id}}"
        >
        <label for="choise{{ forloop.counter }}">
            {{choise.choise_text}}
        </label>
        <br>

    {% endfor %}
</fieldset>
<input type="submit" value="votar">
</form>

<!--<h1>{{question.question_text }}</h1>
<ul>
    {% for choise in question.choise_set.all %}
        <li>{{choise.choise_text}}</li>
    {% endfor %}
</ul>-->

cursodjangoapp/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list  %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are avaliable.</p>
{% endif %}